name: Test cross-platform reproducible builds

on:
  push:
    branches: [ main ]
    paths:
      - 'devenv.nix'
      - 'devenv.lock'
      - '.github/workflows/**'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-python-ubuntu:
    name: Test Python 3.12 (Ubuntu)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install Nix
        uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes
            
      - name: Install devenv
        run: |
          nix profile install --accept-flake-config "github:cachix/devenv/latest"
          devenv --version
          
      - name: Generate requirements and lock files
        run: |
          devenv shell -- generate-requirements
          devenv shell -- update-lock-files
          cat requirements.in
          cat uv.lock
      
      - name: Install pytest
        run: |
          devenv shell -- uv pip install pytest
          
      - name: Run tests with devenv
        run: |
          devenv shell -- python --version
          devenv shell -- uv --version
          devenv shell -- install-from-lock
          devenv shell -- pytest tests/

  test-python-macos:
    name: Test Python 3.12 (macOS)
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install Nix
        uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes
            
      - name: Install devenv
        run: |
          nix profile install --accept-flake-config "github:cachix/devenv/latest"
          devenv --version
          
      - name: Generate requirements and lock files
        run: |
          devenv shell -- generate-requirements
          devenv shell -- update-lock-files
          cat requirements.in
          cat uv.lock
      
      - name: Install pytest
        run: |
          devenv shell -- uv pip install pytest
          
      - name: Run tests with devenv
        run: |
          devenv shell -- python --version
          devenv shell -- uv --version
          devenv shell -- install-from-lock
          devenv shell -- pytest tests/

  test-python-windows:
    name: Test Python 3.12 (Windows)
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            git
            base-devel
            mingw-w64-x86_64-toolchain
            curl
            xz
      
      - name: Install Nix
        run: |
          curl -L https://nixos.org/nix/install | sh -s -- --no-daemon --yes
          echo "source ~/.nix-profile/etc/profile.d/nix.sh" >> ~/.bashrc
          source ~/.nix-profile/etc/profile.d/nix.sh
          mkdir -p ~/.config/nix
          echo "experimental-features = nix-command flakes" >> ~/.config/nix/nix.conf
      
      - name: Install devenv
        run: |
          source ~/.nix-profile/etc/profile.d/nix.sh
          nix profile install --accept-flake-config "github:cachix/devenv/latest"
          devenv --version
          
      - name: Generate requirements and lock files
        run: |
          source ~/.nix-profile/etc/profile.d/nix.sh
          devenv shell -- generate-requirements
          devenv shell -- update-lock-files
          cat requirements.in
          cat uv.lock
      
      - name: Install pytest
        run: |
          source ~/.nix-profile/etc/profile.d/nix.sh
          devenv shell -- uv pip install pytest
          
      - name: Run tests with devenv
        run: |
          source ~/.nix-profile/etc/profile.d/nix.sh
          devenv shell -- python --version
          devenv shell -- uv --version
          devenv shell -- install-from-lock
          devenv shell -- pytest tests/