# name: Test ubuntu reproducible build
# on:
#   push:
#     branches: [ main ]
#     paths:
#       - 'devenv.nix'
#       - 'devenv.lock'
#       - '.github/workflows/**'
#   pull_request:
#     branches: [ main ]
#   workflow_dispatch:

# jobs:
#   test-python:
#     name: Test Python 3.12
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4
      
#       - name: Install Nix
#         uses: cachix/install-nix-action@v22
#         with:
#           nix_path: nixpkgs=channel:nixos-unstable
#           extra_nix_config: |
#             experimental-features = nix-command flakes
      
#       - name: Install devenv
#         run: |
#           nix profile install --accept-flake-config "github:cachix/devenv/latest"
#           devenv --version
     
#       - name: Generate requirements and lock files
#         run: |
#           devenv shell -- generate-requirements
#           devenv shell -- update-lock-files
#           cat requirements.in
#           cat uv.lock
      
#       - name: Run tests with devenv
#         run: |
#           devenv shell -- python --version
#           devenv shell -- uv --version
#           devenv shell -- install-from-lock
#           devenv shell -- pytest tests/

name: Test cross-platform reproducible builds

on:
  push:
    branches: [ main ]
    paths:
      - 'devenv.nix'
      - 'devenv.lock'
      - '.github/workflows/**'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-python-ubuntu:
    name: Test Python 3.12 (Ubuntu)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install Nix
        uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes
            
      - name: Install devenv
        run: |
          nix profile install --accept-flake-config "github:cachix/devenv/latest"
          devenv --version
          
      - name: Generate requirements and lock files
        run: |
          devenv shell -- generate-requirements
          devenv shell -- update-lock-files
          cat requirements.in
          cat uv.lock
          
      - name: Run tests with devenv
        run: |
          devenv shell -- python --version
          devenv shell -- uv --version
          devenv shell -- install-from-lock
          devenv shell -- pytest tests/

  test-python-macos:
    name: Test Python 3.12 (macOS)
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install Nix
        uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes
            
      - name: Install devenv
        run: |
          nix profile install --accept-flake-config "github:cachix/devenv/latest"
          devenv --version
          
      - name: Generate requirements and lock files
        run: |
          devenv shell -- generate-requirements
          devenv shell -- update-lock-files
          cat requirements.in
          cat uv.lock
          
      - name: Run tests with devenv
        run: |
          devenv shell -- python --version
          devenv shell -- uv --version
          devenv shell -- install-from-lock
          devenv shell -- pytest tests/

  test-python-windows:
    name: Test Python 3.12 (Windows)
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup WSL
        uses: Vampire/setup-wsl@v2
        with:
          distribution: Ubuntu-22.04
          wsl-shell-user: root
          additional-packages: 
            curl
            xz-utils
            build-essential
            git
            sudo
      
      - name: Setup WSL Project Directory
        run: |
          wsl -d Ubuntu-22.04 -e bash -c "mkdir -p /github/workspace"
          wsl -d Ubuntu-22.04 -e bash -c "cp -r ${{ github.workspace }}/* /github/workspace/ || true"
        shell: cmd
        
      - name: Install Nix in WSL
        run: |
          wsl -d Ubuntu-22.04 -e bash -c "
            sh <(curl -L https://nixos.org/nix/install) --daemon --yes
            . /etc/profile.d/nix.sh
            echo 'experimental-features = nix-command flakes' >> /etc/nix/nix.conf
            systemctl restart nix-daemon || true
          "
        shell: cmd
      
      - name: Install devenv in WSL
        run: |
          wsl -d Ubuntu-22.04 -e bash -c "
            . /etc/profile.d/nix.sh
            nix profile install --accept-flake-config 'github:cachix/devenv/latest'
            devenv --version
          "
        shell: cmd
          
      - name: Generate requirements and lock files in WSL
        run: |
          wsl -d Ubuntu-22.04 -e bash -c "
            . /etc/profile.d/nix.sh
            cd /github/workspace
            devenv shell -- generate-requirements
            devenv shell -- update-lock-files
            cat requirements.in
            cat uv.lock
          "
        shell: cmd
          
      - name: Run tests with devenv in WSL
        run: |
          wsl -d Ubuntu-22.04 -e bash -c "
            . /etc/profile.d/nix.sh
            cd /github/workspace
            devenv shell -- python --version
            devenv shell -- uv --version
            devenv shell -- install-from-lock
            devenv shell -- pytest tests/
          "
        shell: cmd
